### ISSUE TITLE
Does not display correct time took to complete

### ISSUE THREAD

**Issue by nidhind** [vladmihalcea/vladmihalcea.wordpress.com#3]
https://github.com/vladmihalcea/vladmihalcea.wordpress.com/blob/master/mongodb-facts/data-generator/timeseries/create_random.js#L32

This line does not print the exact time taken by MongoDB to write the data. In-fact when I ran the code in my healthy local Ubuntu system, it said all the documents were written but when I checked the MonogDB collection count, it was increasing every second. Actually what happens is, when lot of concurrent write requests are issued, MongoDB does not write them immediately. It will store it somewhere and eventually complete the write. So what you are displaying is not the actual write rate of MongoDB but only the docs queued to be written. Please verify

**Comment by vladmihalcea** [comment]
It all depends on the [write-concern](https://docs.mongodb.org/manual/reference/write-concern/). With that MongoDB version that I checked back then, the writes were acknowledged.
