### ISSUE TITLE
Can you provied database Structure?

### ISSUE THREAD

**Issue by Sanketp1997** [vladmihalcea/vladmihalcea.wordpress.com#5]

**Comment by vladmihalcea** [comment]
What database structure? For what exactly? Also, this repository is very old, and haven't been using it for years. You might want to check the [high-performance-java-persistence](https://github.com/vladmihalcea/high-performance-java-persistence) instead.

**Comment by Sanketp1997** [comment]
Okay thanks for quick response. :)
